export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const GET_MOVIES_BY_PAGE = 'GET_MOVIES_BY_PAGE';
export const SET_TOTAL_MOVIES = 'SET_TOTAL_MOVIES';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const SET_MOVIE = 'SET_MOVIE';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const REACT_ON_MOVIE = 'REACT_ON_MOVIE';
export const UPDATE_MOVIE_REACTIONS = 'UPDATE_MOVIE_REACTIONS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const LOAD_MORE_COMMENTS = 'LOAD_MORE_COMMENTS';
export const FETCH_MORE_COMMENTS = 'FETCH_MORE_COMMENTS';
export const POST_COMMENT = 'POST_COMMENT';
export const LOAD_NEW_COMMENT = 'LOAD_NEW_COMMENT';
export const INCREMENT_VIEWS = 'INCREMENT_VIEWS';
export const UPDATE_VIEWS = 'UPDATE_VIEWS';

export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';