export const GET_WATCHLIST = 'GET_WATCHLIST';
export const SET_WATCHLIST = 'SET_WATCHLIST';
export const POST_NEW_WATCHLIST_ITEM = 'POST_NEW_WATCHLIST_ITEM';
export const UPDATE_NEW_WATCHLIST_ITEM = 'UPDATE_NEW_WATCHLIST_ITEM';
export const EDIT_WATCHLIST_ITEM = 'EDIT_WATCHLIST_ITEM';
export const UPDATE_EDIT_WATCHLIST_ITEM = 'UPDATE_EDIT_WATCHLIST_ITEM';
export const REMOVE_WATCHLIST_ITEM = 'REMOVE_WATCHLIST_ITEM';
export const UPDATE_REMOVE_WATCHLIST_ITEM = 'UPDATE_REMOVE_WATCHLIST_ITEM';